name: CI
# see https://github.com/orgs/community/discussions/57724
permissions: write-all
on:
  workflow_dispatch:
  push:
    branches: [ master, dev, cut-cookie ]
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'
jobs:

  docker-teximage-build:
    name: Docker Tex Image Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          push: true
          tags: "GITHUB_ACTION_${{ github.run_number }}_TEXIMAGE"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: mmore500/hstrat-algorithm-analysis
          registry: ghcr.io
          path: ./tex/
          add_git_labels: true

  py-unit:
    name: Pylib Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        # with:
        #   submodules: 'recursive'
      - run: python3 -m pip install --upgrade pip
      - run: python3 -m pip install -r requirements.txt
      - run: python3 -m pytest pylib/test/


  binder:
    name: Notebooks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        # with:
        #   submodules: 'recursive'
      - run: python3 -m pip install -r requirements.txt
      # Adapted from https://askubuntu.com/a/524368
      - run: cd binder && ./execute_notebooks.sh
      # adapted from https://unix.stackexchange.com/a/545630
      # - run: find -type f -name "*.pdf" -exec bash -c 'gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dBATCH -dQUIET -sOutputFile="new.pdf" "{}"; rm "{}"; mv "new.pdf" "{}";' {} \;
      - uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          folder: .
          branch: binder # The branch the action should deploy to.

  latex:
    name: Latex Build
    runs-on: ubuntu-22.04
    needs:
      - docker-teximage-build
    container:
      image: ghcr.io/mmore500/hstrat-algorithm-analysis:GITHUB_ACTION_${{ github.run_number }}_TEXIMAGE
      # github actions requires root to access mounted volumes
      options: --user root
    permissions:
      contents: write
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: tree tex  # debug
      - name: Build LaTeX document
        run: |
          trap 'cat tex/*.log || true >> "$GITHUB_OUTPUT"' EXIT
          make -C tex
      - name: Prepare deploy directory
        run: |
          mkdir -p deploy
          cp tex/${{ github.event.repository.name }}-draft.pdf deploy/
          echo '<html><body><a href="${{ github.event.repository.name }}-draft.pdf">Download Manuscript Draft [PDF]</a></body></html>' > deploy/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: deploy
        if: github.ref == 'refs/heads/master'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        if: github.ref == 'refs/heads/master'
